#!/bin/sh

# xkmap-set - run this during X start to set the keyboard selected by xkmap

if [ -f ~/.xkmap.conf ]; then
    cfile="$( readlink -f ~/.xkmap.conf )"
elif [ -f /etc/X11/xinit/xkmap.conf ]; then
    cfile="/etc/X11/xinit/xkmap.conf"
else
    echo "xkmap-set: Error, no settings file found." 1>&2
    echo "       (/etc/X11/xinit/xkmap.conf or ~/.xkmap.conf)" 1>&2
    exit 1
fi

read model layout variant <${cfile}
if [ "${variant}" = "Standard" ]; then
    variant = '""'
fi

setxkbmap -rules xorg -model ${model} -layout ${layout} -variant ${variant}
