#!/bin/sh

# merge_overlay   - recreate 'mods' squashfs

# Author: Michael Towers <gradgrind[at]online[dot]de>
#
# This file is part of the larch project.
#
#    larch is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    larch is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with larch; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#----------------------------------------------------------------------------
# 2008.03.04

# Currently only supports aufs (not unionfs).

# test if the script is started by root user. If not, exit
if [ $UID -ne 0 ]; then
    echo "Only root can run ${APP}"; exit 1
fi

# Underlying system:        /.livesys/system
# 'mods' layer:             /.livesys/mods
# 'home' layer:		    /.livesys/home
# Overlay:                  /.livesys/overlay

# The overlay device (where the archives will be saved)
if [ -d "$1" ]; then
    overlaypath="$1"
else
    echo "ERROR: invalid directory ($1)"
    exit 1
fi

utype="$( cat /.livesys/utype )"
if [ "${utype}" = "unionfs" ]; then
    sqfmnt="ro"
    ovlmnt="ro"
    ovl2mnt="ro"
    bropt="dirs="
    opq=".wh.__dir_opaque"
    whlink="???"
    echo "Overlay merging is currently not implemented for unionfs"
    exit 1
else
    if [ "${utype}" != "aufs" ]; then
        echo "ERROR: bad union type (${utype}), trying aufs"
        utype="aufs"
    fi
    sqfmnt="rr"
    ovlmnt="rr+wh"
    ovl2mnt="ro+wh"
    bropt="br:"
    opq=".wh..wh..opq"
    whlink=".wh..wh.aufs .wh..wh.plink"

    # flush pseudo-links (which keep track of changed hard linked files)
    auplink / flush
fi

if [ -f ${overlaypath}/larch/merge-adjust ] ; then
    . ${overlaypath}/larch/merge-adjust
fi

# Make a directory for a merged union
merge_union=/.livesys/merge_union
rm -rf ${merge_union}
mkdir -p ${merge_union}

echo "Mounting merge union"
# This is using a new feature of aufs, to show whiteouts.
layers="/.livesys/overlay=${ovl2mnt}:/.livesys/mods=${ovlmnt}"
mount -t ${utype} -o ro,shwh,${bropt}${layers} ${utype} ${merge_union}
if [ -d /.livesys/home ]; then
	mount -o remount,append:/.livesys/home=${ovlmnt} ${merge_union}
fi

echo "Rebuilding 'mods' overlay to ${overlaypath}/mods.tmp"
# Recreate the desired layout in a new directory, using mount --bind
# ( this is probably over-complicated, but I got annoying warnings about
#   conflicting permissions on the mount point when I didn't use a single
#   source for squashfs - for some reason the squashfs root was set to
#   mode 0777.)
# The other version was:
## root directories which are included in mods.sqf
#includedirs=""
#for d in bin boot home lib mnt opt root sbin srv usr var; do
#    if [ -d ${merge_union}/${d} ]; then
#        includedirs="${includedirs} ${merge_union}/${d}"
#    fi
#done
## non-included /var directories
#vardirs="${merge_union}/var/log ${merge_union}/var/tmp ${merge_union}/var/cache/pacman/pkg"
#mksquashfs ${includedirs} "${overlaypath}/mods.tmp" -e ${vardirs}
res=$?
#+++
mods2=/.livesys/mods2
rm -rf ${mods2}
mkdir -p ${mods2}
# root directories which are included in mods.sqf
includedirs=""
for d in bin boot lib mnt opt root sbin srv usr var; do
    if [ -d ${merge_union}/${d} ]; then
        includedirs="${includedirs} ${d}"
        mkdir ${mods2}/${d}
        mount --bind ${merge_union}/${d} ${mods2}/${d}
    fi
done

# non-included /var directories
vardirs="var/log var/tmp var/cache/pacman/pkg"
mksquashfs ${mods2} "${overlaypath}/mods.tmp" -e ${vardirs} -noappend
res=$?
for d in ${includedirs}; do
    umount ${mods2}/${d}
done
rm -r ${mods2}
#---
if [ ${res} -ne 0 ]; then
    echo "ERROR: Couldn't create ${overlaypath}/mods.tmp"
    rm -f "${overlaypath}/mods.tmp"
    exit 1
fi

if [ -d ${merge_union}/home ]; then
	echo "Rebuilding 'home' overlay to ${overlaypath}/home.tmp"
	home2=/.livesys/home2
	rm -rf ${home2}
	mkdir -p ${home2}/home
	mount --bind ${merge_union}/home ${home2}/home

	# excluded directories
	vardirs=""
	mksquashfs ${home2} "${overlaypath}/home.tmp" -e ${vardirs} -noappend
	res=$?
	umount ${home2}/home
	rm -r ${home2}
	if [ ${res} -ne 0 ]; then
		echo "ERROR: Couldn't create ${overlaypath}/home.tmp"
		rm -f "${overlaypath}/home.tmp"
		exit 1
	fi
fi

# Discard merge union
umount ${merge_union}
rm -r ${merge_union}

echo "Recreating top overlay to ${overlaypath}/overlay.ovl_"
# Compress the overlay (with root dir 'overlay' retained)
tar -cf - -C /.livesys overlay/etc | lzop > ${overlaypath}/overlay.ovl_
if [ $? -ne 0 ]; then
    echo "ERROR: couldn't create ${overlaypath}/overlay.ovl_"
    rm -f ${overlaypath}/overlay.ovl_
    exit 1
fi

echo "Renaming *.tmp to *.sqf_"
mv "${overlaypath}/mods.tmp" "${overlaypath}/mods.sqf_"
mv "${overlaypath}/home.tmp" "${overlaypath}/home.sqf_"
echo "merging finished"

exit 0
